from src.core.exceptions.database_exceptions import (
    BaseDatabaseException,
    UserNotFoundException,
    UserUsernameAlreadyExistsException,
    UserEmailAlreadyExistsException,
    CategoryNotFoundException,
    CategorySlugAlreadyExistsException,
    LocationNotFoundException,
    PostNotFoundException,
    CommentNotFoundException,
    DatabaseConnectionError,
    DatabaseIntegrityError,
    DatabaseOperationalError,
    DatabaseTimeoutError,
    handle_database_exception,
)
from src.core.exceptions.domain_exceptions import (
    BaseDomainException,
    UserNotFoundByIdException,
    UserNotFoundByUsernameException,
    UserUsernameOrEmailIsNotUniqueException,
    CategoryNotFoundByIdException,
    CategoryNotFoundBySlugException,
    LocationNotFoundByIdException,
    PostNotFoundByIdException,
    PostNotFoundException,
    CommentNotFoundByIdException,
    AuthorNotFoundException,
)

__all__ = [
    # Database exceptions
    'BaseDatabaseException',
    'UserNotFoundException',
    'UserUsernameAlreadyExistsException',
    'UserEmailAlreadyExistsException',
    'CategoryNotFoundException',
    'CategorySlugAlreadyExistsException',
    'LocationNotFoundException',
    'PostNotFoundException',
    'CommentNotFoundException',
    'DatabaseConnectionError',
    'DatabaseIntegrityError',
    'DatabaseOperationalError',
    'DatabaseTimeoutError',
    'handle_database_exception',
    # Domain exceptions
    'BaseDomainException',
    'UserNotFoundByIdException',
    'UserNotFoundByUsernameException',
    'UserUsernameOrEmailIsNotUniqueException',
    'CategoryNotFoundByIdException',
    'CategoryNotFoundBySlugException',
    'LocationNotFoundByIdException',
    'PostNotFoundByIdException',
    'PostNotFoundException',
    'CommentNotFoundByIdException',
    'AuthorNotFoundException',
]
