from src.core.exceptions.database_exceptions import (
    BaseDatabaseException,
    UserNotFoundException,
    UserAlreadyExistsException,
    CategoryNotFoundException,
    CategorySlugAlreadyExistsException,
    LocationNotFoundException,
    PostNotFoundException,
    CommentNotFoundException,
    AuthorNotFoundException,
)
from src.core.exceptions.domain_exceptions import (
    BaseDomainException,
    UserNotFoundByIdException,
    UserNotFoundByUsernameException,
    UserNotFoundByEmailException,
    UserUsernameOrEmailIsNotUniqueException,
    CategoryNotFoundByIdException,
    CategoryNotFoundBySlugException,
    CategorySlugAlreadyExistsException,
    LocationNotFoundByIdException,
    PostNotFoundByIdException,
    CommentNotFoundByIdException,
    AuthorNotFoundException as DomainAuthorNotFoundException,
)

__all__ = [
    # Database exceptions
    'BaseDatabaseException',
    'UserNotFoundException',
    'UserAlreadyExistsException',
    'CategoryNotFoundException',
    'CategorySlugAlreadyExistsException',
    'LocationNotFoundException',
    'PostNotFoundException',
    'CommentNotFoundException',
    'AuthorNotFoundException',
    # Domain exceptions
    'BaseDomainException',
    'UserNotFoundByIdException',
    'UserNotFoundByUsernameException',
    'UserNotFoundByEmailException',
    'UserUsernameOrEmailIsNotUniqueException',
    'CategoryNotFoundByIdException',
    'CategoryNotFoundBySlugException',
    'CategorySlugAlreadyExistsException',
    'LocationNotFoundByIdException',
    'PostNotFoundByIdException',
    'CommentNotFoundByIdException',
    'DomainAuthorNotFoundException',
]
