"""init_db

Revision ID: 6b4257a01b86
Revises: 
Create Date: 2026-05-22 09:27:41.475770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b4257a01b86'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('password', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('username', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('first_name', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('last_name', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('email', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('date_joined', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='application'
    )
    op.create_index(op.f('ix_application_auth_user_email'), 'auth_user', ['email'], unique=False, schema='application')
    op.create_index(op.f('ix_application_auth_user_username'), 'auth_user', ['username'], unique=True, schema='application')
    op.create_table('blog_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('description', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('slug', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    schema='application'
    )
    op.create_table('blog_location',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='application'
    )
    op.create_table('blog_post',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('text', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('pub_date', sa.DateTime(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('image', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['application.auth_user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['application.blog_category.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['application.blog_location.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='application'
    )
    op.create_index(op.f('ix_application_blog_post_author_id'), 'blog_post', ['author_id'], unique=False, schema='application')
    op.create_index(op.f('ix_application_blog_post_category_id'), 'blog_post', ['category_id'], unique=False, schema='application')
    op.create_index(op.f('ix_application_blog_post_location_id'), 'blog_post', ['location_id'], unique=False, schema='application')
    op.create_table('blog_comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['application.auth_user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['application.blog_post.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='application'
    )
    op.create_index(op.f('ix_application_blog_comment_author_id'), 'blog_comment', ['author_id'], unique=False, schema='application')
    op.create_index(op.f('ix_application_blog_comment_post_id'), 'blog_comment', ['post_id'], unique=False, schema='application')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_blog_comment_post_id'), table_name='blog_comment', schema='application')
    op.drop_index(op.f('ix_application_blog_comment_author_id'), table_name='blog_comment', schema='application')
    op.drop_table('blog_comment', schema='application')
    op.drop_index(op.f('ix_application_blog_post_location_id'), table_name='blog_post', schema='application')
    op.drop_index(op.f('ix_application_blog_post_category_id'), table_name='blog_post', schema='application')
    op.drop_index(op.f('ix_application_blog_post_author_id'), table_name='blog_post', schema='application')
    op.drop_table('blog_post', schema='application')
    op.drop_table('blog_location', schema='application')
    op.drop_table('blog_category', schema='application')
    op.drop_index(op.f('ix_application_auth_user_username'), table_name='auth_user', schema='application')
    op.drop_index(op.f('ix_application_auth_user_email'), table_name='auth_user', schema='application')
    op.drop_table('auth_user', schema='application')
    # ### end Alembic commands ###
