"""Initial migration: create all tables

Revision ID: 6db7cf1de472
Revises: 
Create Date: 2026-03-26 19:09:03.470015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6db7cf1de472'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('date_joined', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_user_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_user_username'), ['username'], unique=True)

    op.create_table('blog_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('blog_location',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blog_post',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('pub_date', sa.DateTime(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['auth_user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['blog_category.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['blog_location.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_post_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_post_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_post_location_id'), ['location_id'], unique=False)

    op.create_table('blog_comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['auth_user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['blog_post.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blog_comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_comment_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_comment_post_id'), ['post_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_comment_post_id'))
        batch_op.drop_index(batch_op.f('ix_blog_comment_author_id'))

    op.drop_table('blog_comment')
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_post_location_id'))
        batch_op.drop_index(batch_op.f('ix_blog_post_category_id'))
        batch_op.drop_index(batch_op.f('ix_blog_post_author_id'))

    op.drop_table('blog_post')
    op.drop_table('blog_location')
    op.drop_table('blog_category')
    with op.batch_alter_table('auth_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_user_username'))
        batch_op.drop_index(batch_op.f('ix_auth_user_email'))

    op.drop_table('auth_user')
    # ### end Alembic commands ###
